server_list:
  - endpoint: 127.0.0.1:5000
    weight: 0.5
connection_protocol: http
autocert: false
autocert_hosts:
  - example.com
  - anotherone.com
ssl_certificate: ./server.crt
ssl_private_key: ./server.key
http_port: 1447
tls_port: 443
read_timeout: 5
write_timeout: 10
server_check_timer: 1
server_check_timeout: 1
session_persistence: false
session_max_age: 300
gzip_response: true
rate_limit: false
rate_per_second: 200
rate_bucket: 450
transparent_proxy: true
balancing_algorithm: weighted-least-connections
cache:
  enabled: true
  shards_amount: 8
  shard_size: 128
  algorithm: LFU
  shard_exceed_fallback: false
  background_update: true
  rules:
    - path: /static/
      ttl: 100.Minute
serve_static: false
static_folder: /Projects/static/
static_alias: /static/